name: Publish

on: [push]

jobs:
  # TODO add 'main' branch filter
  build_and_deploy_artifact:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.9
    environment:
      name: staging # uploads to test.pypi.org
      url: https://test.pypi.org/project/biocypher/
    permissions:
      id-token: write
      contents: write
    steps:
    #----------------------------------------------
    # check-out repo and set-up python and poetry
    #----------------------------------------------
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{env.PYTHON_VERSION}}
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
        virtualenvs-create: false
    #----------------------------------------------
    #             install dependencies
    #----------------------------------------------
    - name: Install Dependencies
      run: poetry install
    #----------------------------------------------
    #             build artifact
    #----------------------------------------------
    - name: Build artifact
      run: poetry build
    #----------------------------------------------
    #             upload to PyPi
    #----------------------------------------------
    - name: Publish artifact to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
    #----------------------------------------------
    #           create Github release
    #----------------------------------------------
    - name: Create Github release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
      run: |
        gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="$tag" \
            --generate-notes
